[package]
name = "example-j1939-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "can_echo_pgns"
path = "src/echo_pgns.rs"

[dependencies]
canparse = { version="0.1", features=["use-socketcan"] }
socketcan = "1.7.0"
clap = { version = "3.0", features = ["derive"] }
git-version = "0.3.5"
