[package]
name = "example-j1939-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
canparse = { version="0.1", features=["use-socketcan"] }
socketcan = "1.7.0"

[[bin]]
name = "can_echo_pgns"
path = "src/echo_pgns.rs"
